### ISSUE TITLE
On click of the data table row, show tooltip on territory selected

### ISSUE THREAD

**Issue by ferideadili** [crtarsorg/izborna-platforma#49]

**Comment by artaabdullahu** [comment]
I can not excepted because when I click on data row is show tooltip. In this part I suggest this tooltip to move a little because I can not to see restricted area like this : 
![image](https://cloud.githubusercontent.com/assets/21961919/22460416/12cf0d3c-e7a5-11e6-9b4d-e4f9c8faf710.png)
Look how we have:
![image](https://cloud.githubusercontent.com/assets/21961919/22460487/53713c66-e7a5-11e6-9245-178c6e1a71d3.png)
